postsubmits:
  alunsin/docker-ce-build:
    - name: postsubmit-build-docker-al
      cluster: k8s-ppc64le-cluster
      decorate: true
      branches:
        - dev-docker-build
      run_if_changed: 'env/env.list'
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          job_states_to_report:
           - success
           - failure
           - error
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build
          command:
          - /bin/bash
          args:
          - -c
          - |
            echo "Debug git remote"
            echo "PULL_BASE_REF=$PULL_BASE_REF"
            git remote -v

            cp /etc/ssh-key/ssh-privatekey  ~/.ssh/id_rsa
            git remote add origin git@github.com:alunsin/docker-ce-build.git
            git branch --set-upstream-to origin dev-docker-build

            git config --global user.email "ppc64le@in.ibm.com"
            git config --global user.name "Runtime Team Jobs"

            sleep 600
            exit 1

            #git clone https://alunsin:${GIT_SECRET_AUTH}@github.com/alunsin/docker-ce-build.git
            cd docker-ce-build
            git checkout dev-docker-build
            chmod a+x *.sh
            ./prow-build-docker.sh
            exit_code_script=`echo $?`
            echo "Exit code of the script prow-build-docker : $exit_code_script"
            pid=`/usr/bin/pgrep dockerd`
            echo "Pid of dockerd : $pid"
            if [[ $exit_code_script -eq 0 ]]
            then
              echo "Success"
              kill $pid
              exit 0
            else
              echo "Fail"
              kill $pid
              exit 1
            fi
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-root
            mountPath: /var/lib/docker
          - name: ssh-key
            readOnly: true
            mountPath: /etc/ssh-key
          env:
            - name: S3_SECRET_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-s3-credentials
                  key: password
          # resources:
          #   requests:
          #     cpu: 4000m
          #     memory: 8Gi
          #   limits:
          #     cpu: 4000m
          #     memory: 8Gi
        volumes:
        - name: docker-root
          emptyDir: {}
        - name: ssh-key
          secret:
            secretName: git-ssh-docker-ce-build

    - name: postsubmit-build-containerd
      cluster: k8s-ppc64le-cluster
      decorate: true
      decoration_config:
        timeout: 2h30m
      run_if_changed: 'env/date.list'
      branches:
        - main
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          job_states_to_report:
           - success
           - failure
           - error
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build
          command:
          - /bin/bash
          args:
          - -c
          - |
            cd ..
            rm -rf docker-ce-build
            git clone https://github.com/florencepascual/docker-ce-build
            cd docker-ce-build
            chmod a+x *.sh
            ./prow-build-containerd.sh
            exitCode_script=`echo $?`
            echo "Exit code of the script prow-build-containerd : $exitCode_script"
            pid=`/usr/bin/pgrep dockerd`
            echo "Pid of dockerd : $pid"
            if [[ $exitCode_script -eq 0 ]]
            then
              echo "Success"
              kill $pid
              exit 0
            else
              echo "Fail"
              kill $pid
              exit 1
            fi
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-root
            mountPath: /var/lib/docker
          env:
            - name: S3_SECRET_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-s3-credentials
                  key: password
            - name: DOCKER_SECRET_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-token
                  key: .dockerconfigjson
          resources:
            requests:
              cpu: 4000m
              memory: 8Gi
            limits:
              cpu: 4000m
              memory: 8Gi
        volumes:
        - name: docker-root
          emptyDir: {}
