postsubmits:
 #ppc64le-cloud/docker-ce-build:
  alunsin/docker-ce-build:
    - name: postsubmit-build-docker
      cluster: k8s-ppc64le-cluster
      decorate: true
      branches:
        - dev-docker-build
        # -  main
      run_if_changed: 'env/env.list'
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          job_states_to_report:
           - success
           - failure
           - error
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build
          command:
          - /bin/bash
          args:
          - -c
          - |
            set -x

            #Configure git SSH key from ssh-key secret
            mkdir -p ~/.ssh
            cp /etc/ssh-key/ssh-privatekey  ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

            ./prow-build-docker.sh
            exit_code_script=`echo $?`
            echo "Exit code of the script prow-build-docker : $exit_code_script"
            if [[ $exit_code_script -eq 0 ]]
            then
              exit 0
            else
              exit 1
            fi
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-root
            mountPath: /var/lib/docker
          - name: ssh-key
            readOnly: true
            mountPath: /etc/ssh-key
          env:
            - name: S3_SECRET_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-s3-credentials
                  key: password
          # resources:
          #   requests:
          #     cpu: 4000m
          #     memory: 8Gi
          #   limits:
          #     cpu: 4000m
          #     memory: 8Gi
        volumes:
        - name: docker-root
          emptyDir: {}
        - name: ssh-key
          secret:
#            secretName: git-ssh-docker-ce-build
            secretName: git-ssh-alunsin-docker-ce-build

    - name: postsubmit-build-containerd
      cluster: k8s-ppc64le-cluster
      decorate: true
      decoration_config:
        timeout: 2h30m
      run_if_changed: 'env/date.list'
      branches:
        - main
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          job_states_to_report:
           - success
           - failure
           - error
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build
          command:
          - /bin/bash
          args:
          - -c
          - |
            ##
            # The job is populated with the file from the 'prow-job-tracking'.
            # We need to switch to the main branch which contains the scripts need by this job.
            ###

            #MAIN_BRANCH=main
            MAIN_BRANCH=dev-docker-build
            TRIGER_FILE=postsubmit-build-docker

            #Backup timestamp file from the previous job
            cp job/${TRIGER_FILE} /tmp

            git fetch https://github.com/${REPO_OWNER}/${REPO_NAME} ${MAIN_BRANCH}
            git branch --force ${MAIN_BRANCH} FETCH_HEAD
            git checkout ${MAIN_BRANCH}

            #Restore the timestamp file from the previous job
            cp /tmp/${TRIGER_FILE} env/date.list

            ./prow-build-containerd.sh
            exitCode_script=$?
            echo "Exit code of the script prow-build-containerd : $exitCode_script"
            if [[ $exit_code_script -eq 0 ]]
            then
              exit 0
            else
              exit 1
            fi
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-root
            mountPath: /var/lib/docker
          env:
            - name: S3_SECRET_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-s3-credentials
                  key: password
            - name: DOCKER_SECRET_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-token
                  key: .dockerconfigjson
          resources:
            requests:
              cpu: 4000m
              memory: 8Gi
            limits:
              cpu: 4000m
              memory: 8Gi
        volumes:
        - name: docker-root
          emptyDir: {}
