apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-janitor-nongke
  labels:
    app: boskos-janitor-nongke
  namespace: test-pods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boskos-janitor-nongke
  template:
    metadata:
      labels:
        app: boskos-janitor-nongke
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor-nongke
        image: gcr.io/k8s-staging-boskos/janitor:v20220208-21245b5
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --resource-type=powervs-project
        - --janitor-path=/root/powervs-janitor.sh
        - --pool-size=20
        - --
        - --hours=0
        envFrom:
          - secretRef:
              name: ibm-cloud-credentials
        volumeMounts:
          - mountPath: "/root/powervs-janitor.sh"
            name: janitor-powervs
            subPath: "powervs-janitor.sh"
      volumes:
        - name: janitor-powervs
          configMap:
            name: janitor-powervs
            defaultMode: 0755
