apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-search
  namespace: prow
  labels:
    app: ci-search
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ci-search
  template:
    metadata:
      labels:
        app: ci-search
    spec:
      serviceAccountName: ci-search
      terminationGracePeriodSeconds: 30
      containers:
      - name: ci-search
        image: quay.io/powercloud/ci-search:latest
        ports:
        - containerPort: 8080
